[package]
name = "ucfx_byteswap"
version = "1.0.0"
edition = "2021"

[lib]
name = "ucfx_byteswap"
path = "src/lib.rs"

[[bin]]
name = "ucfx_byteswap"
path = "src/main.rs"

[dependencies]
mercs2_formats = { version = "1.0", path = "../mercs2_formats" }
clap = { version = "4", features = ["derive"] }
