import("MrxSound")
import("MrxMusic")
import("MrxSoundCategories")
import("MrxSoundBanks")

function Init()
  Debug.Printf("SoundShellBootstrap.Init")
  MrxSoundCategories.SetFadeCategory("vosequence", "sfx", 0.4, 0.5, 0.5)
  MrxSoundCategories.SetFadeCategory("vosequence", "chatter", 0.3, 0.5, 0.5)
  MrxSoundCategories.SetFadeCategory("vosequence", "music", 0.8, 0.5, 0.5)
  MrxSoundCategories.SetFadeCategory("actionhijack", "Non_Action_Hijack", 0.4, 0.5, 0.5)
  MrxSoundCategories.SetFadeCategory("actionhijack", "chatter", 0.3, 0.5, 0.5)
  MrxSoundCategories.SetFadeCategory("survivalmode", "sfx", 0.4, 0.5, 0.5)
  MrxSoundCategories.SetFadeCategory("survivalmode", "chatter", 0.3, 0.5, 0.5)
  MrxSoundCategories.SetFadeCategory("survivalmode", "music", 0.8, 0.5, 0.5)
  MrxSoundCategories.SetFadeCategory("fanfare", "sfx", 0.1, 0.5, 0.5)
  MrxSoundCategories.SetFadeCategory("fanfare", "vo", 0.1, 0.5, 0.5)
  MrxSoundCategories.SetFadeCategory("satelliteview", "sfx", 0.1, 0.5, 0.5)
  MrxSoundCategories.SetFadeCategory("satelliteview", "chatter", 0.1, 0.5, 0.5)
  MrxMusic.BindMusicCue("an", "explore", 1, "mu_fac_an_explore_01")
  MrxMusic.BindMusicCue("an", "action", 1, "mu_fac_an_threat_01")
  MrxMusic.BindMusicCue("an", "mission_success", 1, "mu_fac_an_win_01")
  MrxMusic.BindMusicCue("an", "mission_failure", 1, "mu_fac_an_fail_01")
  MrxMusic.BindMusicCue("an", "hijack", 1, "mu_fac_an_hijack_01")
  MrxMusic.BindMusicCue("an", "hijack", 2, "mu_fac_an_hijack_02")
  MrxMusic.BindMusicCue("an", "hijack", 3, "mu_fac_an_hijack_03")
  MrxMusic.BindMusicCue("an", "hijack_success", 1, "mu_fac_an_kickass_01")
  MrxMusic.BindMusicCue("an", "shell", 1, "mu_shell_01")
  MrxMusic.BindMusicCue("an", "pause", 1, "mu_shell_01")
  MrxMusic.BindMusicCue("oc", "explore", 1, "mu_fac_oc_explore_01")
  MrxMusic.BindMusicCue("oc", "action", 1, "mu_fac_oc_threat_01")
  MrxMusic.BindMusicCue("oc", "mission_success", 1, "mu_fac_oc_win_01")
  MrxMusic.BindMusicCue("oc", "mission_failure", 1, "mu_fac_oc_fail_01")
  MrxMusic.BindMusicCue("oc", "hijack", 1, "mu_fac_oc_hijack_01")
  MrxMusic.BindMusicCue("oc", "hijack", 2, "mu_fac_oc_hijack_02")
  MrxMusic.BindMusicCue("oc", "hijack_success", 1, "mu_fac_oc_kickass_01")
  MrxMusic.BindMusicCue("oc", "shell", 1, "mu_shell_01")
  MrxMusic.BindMusicCue("oc", "pause", 1, "mu_shell_01")
  MrxMusic.BindMusicCue("gr", "explore", 1, "mu_fac_gr_explore_01")
  MrxMusic.BindMusicCue("gr", "action", 1, "mu_fac_gr_threat_01")
  MrxMusic.BindMusicCue("gr", "mission_success", 1, "mu_fac_gr_win_01")
  MrxMusic.BindMusicCue("gr", "mission_failure", 1, "mu_fac_gr_fail_01")
  MrxMusic.BindMusicCue("gr", "hijack", 1, "mu_fac_gr_hijack_01")
  MrxMusic.BindMusicCue("gr", "hijack", 2, "mu_fac_gr_hijack_02")
  MrxMusic.BindMusicCue("gr", "hijack", 3, "mu_fac_gr_hijack_03")
  MrxMusic.BindMusicCue("gr", "hijack_success", 1, "mu_fac_gr_kickass_01")
  MrxMusic.BindMusicCue("gr", "shell", 1, "mu_shell_01")
  MrxMusic.BindMusicCue("gr", "pause", 1, "mu_shell_01")
  MrxMusic.BindMusicCue("ch", "explore", 1, "mu_fac_ch_explore_01")
  MrxMusic.BindMusicCue("ch", "action", 1, "mu_fac_ch_threat_01")
  MrxMusic.BindMusicCue("ch", "mission_success", 1, "mu_fac_ch_win_01")
  MrxMusic.BindMusicCue("ch", "mission_failure", 1, "mu_fac_ch_fail_01")
  MrxMusic.BindMusicCue("ch", "hijack", 1, "mu_fac_ch_hijack_01")
  MrxMusic.BindMusicCue("ch", "hijack", 2, "mu_fac_ch_hijack_02")
  MrxMusic.BindMusicCue("ch", "hijack", 3, "mu_fac_ch_hijack_03")
  MrxMusic.BindMusicCue("ch", "hijack_success", 1, "mu_fac_ch_kickass_01")
  MrxMusic.BindMusicCue("ch", "shell", 1, "mu_shell_01")
  MrxMusic.BindMusicCue("ch", "pause", 1, "mu_shell_01")
  MrxMusic.BindMusicCue("pmc", "explore", 1, "mu_fac_pmc_explore_01")
  MrxMusic.BindMusicCue("pmc", "action", 1, "mu_fac_pmc_threat_01")
  MrxMusic.BindMusicCue("pmc", "mission_success", 1, "mu_fac_pmc_win_01")
  MrxMusic.BindMusicCue("pmc", "mission_failure", 1, "mu_fac_pmc_fail_01")
  MrxMusic.BindMusicCue("pmc", "hijack", 1, "mu_fac_oc_hijack_01")
  MrxMusic.BindMusicCue("pmc", "hijack", 2, "mu_fac_oc_hijack_02")
  MrxMusic.BindMusicCue("pmc", "hijack_success", 1, "mu_fac_pmc_kickass_01")
  MrxMusic.BindMusicCue("pmc", "shell", 1, "mu_shell_01")
  MrxMusic.BindMusicCue("pmc", "pause", 1, "mu_shell_01")
  MrxMusic.BindMusicCue("freeplay_city", "explore", 1, "mu_nomission_city_explore_01")
  MrxMusic.BindMusicCue("freeplay_city", "action", 1, "mu_nomission_city_threat_01")
  MrxMusic.BindMusicCue("freeplay_city", "high_action", 1, "mu_nomission_city_threat_02")
  MrxMusic.BindMusicCue("freeplay_city", "mission_failure", 1, "mu_nomission_city_fail_01")
  MrxMusic.BindMusicCue("freeplay_city", "mission_success", 1, "mu_fac_pmc_win_01")
  MrxMusic.BindMusicCue("freeplay_city", "shell", 1, "mu_shell_01")
  MrxMusic.BindMusicCue("freeplay_city", "pause", 1, "mu_shell_01")
  MrxMusic.BindMusicCue("freeplay_jungle", "explore", 1, "mu_nomission_jungle_explore_01")
  MrxMusic.BindMusicCue("freeplay_jungle", "action", 1, "mu_nomission_jungle_threat_01")
  MrxMusic.BindMusicCue("freeplay_jungle", "high_action", 1, "mu_nomission_jungle_threat_02")
  MrxMusic.BindMusicCue("freeplay_jungle", "mission_failure", 1, "mu_nomission_jungle_fail_01")
  MrxMusic.BindMusicCue("freeplay_jungle", "mission_success", 1, "mu_fac_pmc_win_01")
  MrxMusic.BindMusicCue("freeplay_jungle", "shell", 1, "mu_shell_01")
  MrxMusic.BindMusicCue("freeplay_jungle", "pause", 1, "mu_shell_01")
  MrxMusic.BindMusicCue("freeplay_water", "explore", 1, "mu_nomission_water_explore_01")
  MrxMusic.BindMusicCue("freeplay_water", "action", 1, "mu_nomission_water_threat_01")
  MrxMusic.BindMusicCue("freeplay_water", "high_action", 1, "mu_nomission_water_threat_02")
  MrxMusic.BindMusicCue("freeplay_water", "mission_failure", 1, "mu_nomission_water_fail_01")
  MrxMusic.BindMusicCue("freeplay_water", "mission_success", 1, "mu_fac_pmc_win_01")
  MrxMusic.BindMusicCue("freeplay_water", "shell", 1, "mu_shell_01")
  MrxMusic.BindMusicCue("freeplay_water", "pause", 1, "mu_shell_01")
  MrxSound.Initialize()
end

EXITSHELL_FADELENGTH = 0.5

function PreExitShell()
  Sound.SetMasterVolume(0, EXITSHELL_FADELENGTH)
end

function ExitShell()
  MrxSound.ExitShellState()
end
