function OnActivate(guid)
  Event.Create(Event.TimerRelative, {0.1}, _GraphicsAto, {guid})
end

function _GraphicsAto(guid)
  Graphics.Atmosphere.Begin()
  Graphics.Atmosphere.SetColorValue("uiAmbientColor", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube0", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube1", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube2", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube3", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube4", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube5", 128, 128, 128, 255)
  Graphics.Atmosphere.SetValue("fAtmosphereForce", 0)
  Graphics.Atmosphere.SetValue("fAtmosphereLimit", 125)
  Graphics.Atmosphere.SetValue("fBloomAdaptiveLuminancePercent", 0.7)
  Graphics.Atmosphere.SetValue("fBloomAdaptiveLuminanceScale", 20)
  Graphics.Atmosphere.SetValue("fBloomAmount", 0.75)
  Graphics.Atmosphere.SetValue("fBloomBlurRadius", 0.75)
  Graphics.Atmosphere.SetValue("fBloomContastLimit", 0.75)
  Graphics.Atmosphere.SetValue("fBloomContastMultiplier", 1.25)
  Graphics.Atmosphere.SetValue("fBloomMultiplier", 0.55)
  Graphics.Atmosphere.SetValue("fBloomTargetLuminance", 0.75)
  Graphics.Atmosphere.SetValue("fBloomThreshold", 0.75)
  Graphics.Atmosphere.SetColorValue("uiGradient0_Color2", 0, 0, 255, 0)
  Graphics.Atmosphere.SetColorValue("uiGradient1_Color1", 0, 0, 255, 0)
  Graphics.Atmosphere.SetValue("fLightIntensity", 1.55)
  Graphics.Atmosphere.SetColorValue("uiRimColor", 128, 128, 128, 255)
  Graphics.Atmosphere.SetValue("fTimeRestore", 0.5)
  Graphics.Atmosphere.End()
end
