import("MrxUtil")

function OnActivate(guid)
  Event.Create(Event.TimerRelative, {1.75}, _GraphicsAto, {guid})
end

function _GraphicsAto(guid)
  Graphics.Atmosphere.Begin()
  Graphics.Atmosphere.SetColorValue("uiAmbientColor", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube0", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube1", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube2", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube3", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube4", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube5", 128, 128, 128, 255)
  Graphics.Atmosphere.SetValue("fAtmosphereForce", 0)
  Graphics.Atmosphere.SetValue("fAtmosphereLimit", 200)
  Graphics.Atmosphere.SetValue("fBloomAdaptiveLuminancePercent", 0.98)
  Graphics.Atmosphere.SetValue("fBloomAdaptiveLuminanceScale", 30)
  Graphics.Atmosphere.SetValue("fBloomAmount", 1)
  Graphics.Atmosphere.SetValue("fBloomBlurRadius", 1)
  Graphics.Atmosphere.SetValue("fBloomContastLimit", 1)
  Graphics.Atmosphere.SetValue("fBloomContastMultiplier", 1.85)
  Graphics.Atmosphere.SetValue("fBloomMultiplier", 0.8)
  Graphics.Atmosphere.SetValue("fBloomTargetLuminance", 1)
  Graphics.Atmosphere.SetValue("fBloomThreshold", 1)
  Graphics.Atmosphere.SetColorValue("uiGradient0_Color2", 0, 0, 255, 0)
  Graphics.Atmosphere.SetColorValue("uiGradient1_Color1", 0, 0, 255, 0)
  Graphics.Atmosphere.SetValue("fLightIntensity", 2.5)
  Graphics.Atmosphere.SetColorValue("uiRimColor", 128, 128, 128, 255)
  Graphics.Atmosphere.SetValue("fTimeRestore", 1.7)
  Graphics.Atmosphere.End()
  MrxUtil.ShieldFace(guid)
end
