import("MrxUtil")

function OnActivate(guid)
  Event.Create(Event.TimerRelative, {0.1}, _GraphicsAto, {guid})
end

function _GraphicsAto(guid)
  Graphics.Atmosphere.Begin()
  Graphics.Atmosphere.SetColorValue("uiAmbientColor", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube0", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube1", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube2", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube3", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube4", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube5", 128, 128, 128, 255)
  Graphics.Atmosphere.SetValue("fAtmosphereForce", 0)
  Graphics.Atmosphere.SetValue("fAtmosphereLimit", 200)
  Graphics.Atmosphere.SetValue("fBloomAdaptiveLuminancePercent", 0.098)
  Graphics.Atmosphere.SetValue("fBloomAdaptiveLuminanceScale", 3)
  Graphics.Atmosphere.SetValue("fBloomAmount", 0.1)
  Graphics.Atmosphere.SetValue("fBloomBlurRadius", 0.1)
  Graphics.Atmosphere.SetValue("fBloomContastLimit", 0.1)
  Graphics.Atmosphere.SetValue("fBloomContastMultiplier", 0.185)
  Graphics.Atmosphere.SetValue("fBloomMultiplier", 0.08)
  Graphics.Atmosphere.SetValue("fBloomTargetLuminance", 0.1)
  Graphics.Atmosphere.SetValue("fBloomThreshold", 0.1)
  Graphics.Atmosphere.SetValue("fLightIntensity", 0.25)
  Graphics.Atmosphere.SetColorValue("uiRimColor", 128, 128, 128, 255)
  Graphics.Atmosphere.SetValue("fTimeRestore", 0.6)
  Graphics.Atmosphere.End()
  MrxUtil.ShieldFace(guid)
end
