import("MrxUtil")

function OnActivate(guid)
  Event.Create(Event.TimerRelative, {0.1}, _GraphicsAto, {guid})
end

function _GraphicsAto(guid)
  Graphics.Atmosphere.Begin()
  Graphics.Atmosphere.SetColorValue("uiAmbientColor", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube0", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube1", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube2", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube3", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube4", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube5", 128, 128, 128, 255)
  Graphics.Atmosphere.SetValue("fAtmosphereForce", 0)
  Graphics.Atmosphere.SetValue("fAtmosphereLimit", 250)
  Graphics.Atmosphere.SetValue("fBloomAdaptiveLuminancePercent", 0.81)
  Graphics.Atmosphere.SetValue("fBloomAdaptiveLuminanceScale", 25)
  Graphics.Atmosphere.SetValue("fBloomAmount", 0.84)
  Graphics.Atmosphere.SetValue("fBloomBlurRadius", 0.84)
  Graphics.Atmosphere.SetValue("fBloomContastLimit", 0.84)
  Graphics.Atmosphere.SetValue("fBloomContastMultiplier", 1.54)
  Graphics.Atmosphere.SetValue("fBloomMultiplier", 0.66)
  Graphics.Atmosphere.SetValue("fBloomTargetLuminance", 1.25)
  Graphics.Atmosphere.SetValue("fBloomThreshold", 0.84)
  Graphics.Atmosphere.SetColorValue("uiGradient0_Color2", 0, 0, 255, 0)
  Graphics.Atmosphere.SetColorValue("uiGradient1_Color1", 0, 0, 255, 0)
  Graphics.Atmosphere.SetValue("fLightIntensity", 3.75)
  Graphics.Atmosphere.SetColorValue("uiRimColor", 128, 128, 128, 255)
  Graphics.Atmosphere.SetValue("fTimeRestore", 1.7)
  Graphics.Atmosphere.End()
  MrxUtil.ShieldFace(guid)
end
