function OnActivate()
  Graphics.Atmosphere.Begin()
  
  Graphics.Atmosphere.SetColorValue("uiAmbientColor", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube0", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube1", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube2", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube3", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube4", 128, 128, 128, 255)
  Graphics.Atmosphere.SetColorValue("uiAmbientCube5", 128, 128, 128, 255)
  Graphics.Atmosphere.SetValue("fAtmosphereForce", 0)
  Graphics.Atmosphere.SetValue("fAtmosphereLimit", 100)
  Graphics.Atmosphere.SetValue("fBloomAdaptiveLuminancePercent", 0.49)
  Graphics.Atmosphere.SetValue("fBloomAdaptiveLuminanceScale", 15)
  Graphics.Atmosphere.SetValue("fBloomAmount", 0.5)
  Graphics.Atmosphere.SetValue("fBloomBlurRadius", 0.5)
  Graphics.Atmosphere.SetValue("fBloomContastLimit", 0.5)
  Graphics.Atmosphere.SetValue("fBloomContastMultiplier", 0.925)
  Graphics.Atmosphere.SetValue("fBloomMultiplier", 0.8)
  Graphics.Atmosphere.SetValue("fBloomTargetLuminance", 1.5)
  Graphics.Atmosphere.SetValue("fBloomThreshold", 0.8)
  Graphics.Atmosphere.SetColorValue("uiGradient0_Color2", 0, 0, 255, 0)
  Graphics.Atmosphere.SetColorValue("uiGradient1_Color1", 0, 0, 255, 0)
  Graphics.Atmosphere.SetValue("fLightIntensity", 2.5)
  Graphics.Atmosphere.SetColorValue("uiRimColor", 128, 128, 128, 255)
  Graphics.Atmosphere.SetValue("fTimeRestore", 0.55)
  Graphics.Atmosphere.End()
end
