#!/usr/bin/env python3
"""Generate compat_patches.gen.c from patch_anim_table.py's PATCHES table.

This turns the *proven exe-patch* (the 1024->4096 anim-table expansion + the
texture/effect NULL guards) into an in-memory patch table that pmc_bb applies at
runtime via VirtualProtect — so the same fix is delivered WITHOUT editing the EXE.

Run from repo root:  python tools/pmc_blackbox/gen_compat_patches.py
Writes:              tools/pmc_blackbox/compat_patches.gen.c
"""
import importlib.util
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SRC = REPO / "tools" / "patch_anim_table.py"
OUT = REPO / "tools" / "pmc_blackbox" / "compat_patches.gen.c"


def load_patches():
    spec = importlib.util.spec_from_file_location("patch_anim_table", SRC)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.PATCHES


def c_bytes(b: bytes) -> str:
    return "{" + ",".join(f"0x{x:02X}" for x in b) + "}"


def main():
    patches = load_patches()
    lines = [
        "/* AUTO-GENERATED by tools/pmc_blackbox/gen_compat_patches.py — DO NOT EDIT. */",
        "/* Source of truth: tools/patch_anim_table.py PATCHES (the proven exe patch). */",
        "/* These are applied IN MEMORY at runtime by pmc_bb (no EXE edit). */",
        "#include <windows.h>",
        "",
        "typedef struct {",
        "    DWORD va;                 /* absolute VA (IMAGE_BASE 0x400000) */",
        "    const unsigned char *exp; /* expected original bytes */",
        "    const unsigned char *pat; /* patched bytes */",
        "    unsigned int len;",
        "    const char *desc;",
        "} CompatPatch;",
        "",
    ]
    for i, (va, exp, pat, desc) in enumerate(patches):
        assert len(exp) == len(pat), f"len mismatch at 0x{va:X}: {desc}"
        lines.append(f"static const unsigned char e{i}[] = {c_bytes(exp)};")
        lines.append(f"static const unsigned char p{i}[] = {c_bytes(pat)};")
    lines.append("")
    lines.append("const CompatPatch g_compatPatches[] = {")
    for i, (va, exp, pat, desc) in enumerate(patches):
        safe = desc.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    {{0x{va:08X}, e{i}, p{i}, {len(exp)}, "{safe}"}},')
    lines.append("};")
    lines.append("")
    lines.append(f"const unsigned int g_compatPatchCount = {len(patches)};")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(patches)} patches)")


if __name__ == "__main__":
    main()
