LocalWidgetList = {}
if import then
  import("MrxGuiSatellite")
else
  MrxGuiSatellite = {}
end
LocalWidgetList[1] = {
  name = "Satellite overlay",
  x1 = 0,
  y1 = 0,
  x2 = 640,
  y2 = 480,
  RedLevel = 255,
  GreenLevel = 255,
  BlueLevel = 255,
  TranslucencyLevel = 255,
  HorizontalAnchor = "center",
  VerticalAnchor = "center",
  visible = 1,
  container = true,
  EventHandlerFile = "MrxGuiSatellite",
  EventHandlers = {
    GuiInitialization = MrxGuiSatellite.Initialize,
    SatelliteStateChange = MrxGuiSatellite.HandleSatelliteStateChangeEvent
  },
  EventHandlerNames = {
    GuiInitialization = "Initialize",
    SatelliteStateChange = "HandleSatelliteStateChangeEvent"
  },
  Children = {
    {
      name = "Minigame prototype",
      x1 = 0,
      y1 = 0,
      x2 = 640,
      y2 = 480,
      RedLevel = 255,
      GreenLevel = 255,
      BlueLevel = 255,
      TranslucencyLevel = 0,
      HorizontalAnchor = "center",
      VerticalAnchor = "center",
      visible = 1,
      container = true,
      WidgetType = "image",
      texture = nil,
      textureFile = nil,
      rotation = 0,
      u1 = 0,
      v1 = 0,
      u2 = 1,
      v2 = 1,
      EventHandlerFile = "",
      EventHandlers = {},
      EventHandlerNames = {},
      Children = {
        {
          name = "bg circle of DOOM",
          x1 = 192,
          y1 = 112,
          x2 = 448,
          y2 = 368,
          RedLevel = 255,
          GreenLevel = 255,
          BlueLevel = 225,
          TranslucencyLevel = 255,
          HorizontalAnchor = "center",
          VerticalAnchor = "center",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = "global_satellite_circle",
          textureFile = "D:/projects/Branches/Snapshot/Data/Src/Map/GLOBAL/HUD/TEXTURES/global_satellite_circle.tga",
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "wedge1",
          x1 = 192,
          y1 = 112,
          x2 = 448,
          y2 = 368,
          RedLevel = 220,
          GreenLevel = 160,
          BlueLevel = 180,
          TranslucencyLevel = 160,
          HorizontalAnchor = "center",
          VerticalAnchor = "center",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = "global_satellite_wedge",
          textureFile = "D:/projects/Branches/Snapshot/Data/Src/Map/GLOBAL/HUD/TEXTURES/global_satellite_wedge.tga",
          rotation = 90,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "wedge2",
          x1 = 192,
          y1 = 112,
          x2 = 448,
          y2 = 368,
          RedLevel = 220,
          GreenLevel = 160,
          BlueLevel = 180,
          TranslucencyLevel = 160,
          HorizontalAnchor = "center",
          VerticalAnchor = "center",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = "global_satellite_wedge",
          textureFile = "D:/projects/Branches/Snapshot/Data/Src/Map/GLOBAL/HUD/TEXTURES/global_satellite_wedge.tga",
          rotation = 180,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "wedge3",
          x1 = 192,
          y1 = 112,
          x2 = 448,
          y2 = 368,
          RedLevel = 220,
          GreenLevel = 160,
          BlueLevel = 180,
          TranslucencyLevel = 160,
          HorizontalAnchor = "center",
          VerticalAnchor = "center",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = "global_satellite_wedge",
          textureFile = "D:/projects/Branches/Snapshot/Data/Src/Map/GLOBAL/HUD/TEXTURES/global_satellite_wedge.tga",
          rotation = 270,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "cursor of DOOM",
          x1 = 192,
          y1 = 112,
          x2 = 448,
          y2 = 368,
          RedLevel = 255,
          GreenLevel = 0,
          BlueLevel = 255,
          TranslucencyLevel = 255,
          HorizontalAnchor = "center",
          VerticalAnchor = "center",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = "global_satellite_cursor",
          textureFile = "D:/projects/Branches/Snapshot/Data/Src/Map/GLOBAL/HUD/TEXTURES/global_satellite_cursor.tga",
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "feedback",
          x1 = 192,
          y1 = 112,
          x2 = 448,
          y2 = 368,
          RedLevel = 255,
          GreenLevel = 0,
          BlueLevel = 255,
          TranslucencyLevel = 0,
          HorizontalAnchor = "center",
          VerticalAnchor = "center",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = "icon_fail",
          textureFile = "D:/projects/Branches/Snapshot/Data/Src/Map/GLOBAL/HUD/TEXTURES/buttons/icon_fail.tga",
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "satbutton",
          x1 = 192,
          y1 = 112,
          x2 = 448,
          y2 = 368,
          RedLevel = 255,
          GreenLevel = 255,
          BlueLevel = 255,
          TranslucencyLevel = 255,
          HorizontalAnchor = "center",
          VerticalAnchor = "center",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = "Pistol",
          textureFile = "D:/projects/Branches/Snapshot/Data/Src/Map/GLOBAL/HUD/TEXTURES/buttons/Pistol.tga",
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        }
      }
    },
    {
      name = "Background",
      x1 = -160,
      y1 = 0,
      x2 = 800,
      y2 = 480,
      RedLevel = 255,
      GreenLevel = 255,
      BlueLevel = 255,
      TranslucencyLevel = 0,
      HorizontalAnchor = "center",
      VerticalAnchor = "center",
      visible = 1,
      container = true,
      WidgetType = "image",
      texture = nil,
      textureFile = nil,
      rotation = 0,
      u1 = 0,
      v1 = 0,
      u2 = 1,
      v2 = 1,
      EventHandlerFile = "",
      EventHandlers = {},
      EventHandlerNames = {},
      Children = {
        {
          name = "wipe",
          x1 = -160,
          y1 = 0,
          x2 = 800,
          y2 = 70,
          RedLevel = 0,
          GreenLevel = 0,
          BlueLevel = 0,
          TranslucencyLevel = 14,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "MrxGuiSatellite",
          EventHandlers = {
            GuiUpdate = MrxGuiSatellite.WipeUpdate
          },
          EventHandlerNames = {GuiUpdate = "WipeUpdate"},
          Children = {}
        },
        {
          name = "bg",
          x1 = -160,
          y1 = 0,
          x2 = 800,
          y2 = 480,
          RedLevel = 255,
          GreenLevel = 255,
          BlueLevel = 255,
          TranslucencyLevel = 255,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = "scope_interlacing_lines",
          textureFile = "D:/projects/Branches/Snapshot/Data/Src/Map/GLOBAL/HUD/TEXTURES/scope_interlacing_lines.tga",
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          nTileWidth = 8,
          nTileHeight = 8,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "grit",
          x1 = -106.6667,
          y1 = 0,
          x2 = 746.6666,
          y2 = 480,
          RedLevel = 255,
          GreenLevel = 255,
          BlueLevel = 255,
          TranslucencyLevel = 255,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = "scope_texture",
          textureFile = "D:/projects/Branches/Snapshot/Data/Src/Map/GLOBAL/HUD/TEXTURES/scope_texture.tga",
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        }
      }
    },
    {
      name = "Reticle",
      x1 = 280,
      y1 = 200,
      x2 = 360,
      y2 = 280,
      RedLevel = 255,
      GreenLevel = 255,
      BlueLevel = 255,
      TranslucencyLevel = 0,
      HorizontalAnchor = "center",
      VerticalAnchor = "center",
      visible = 1,
      container = true,
      WidgetType = "image",
      texture = nil,
      textureFile = nil,
      rotation = 0,
      u1 = 0,
      v1 = 0,
      u2 = 1,
      v2 = 1,
      EventHandlerFile = "",
      EventHandlers = {},
      EventHandlerNames = {},
      Children = {
        {
          name = "Image",
          x1 = 280,
          y1 = 200,
          x2 = 360,
          y2 = 280,
          RedLevel = 255,
          GreenLevel = 255,
          BlueLevel = 255,
          TranslucencyLevel = 0,
          HorizontalAnchor = "center",
          VerticalAnchor = "center",
          visible = 1,
          container = true,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {
            {
              name = "crosshair",
              x1 = 312,
              y1 = 228,
              x2 = 328,
              y2 = 244,
              RedLevel = 255,
              GreenLevel = 255,
              BlueLevel = 255,
              TranslucencyLevel = 0,
              HorizontalAnchor = "left",
              VerticalAnchor = "top",
              visible = 1,
              container = true,
              WidgetType = "image",
              texture = nil,
              textureFile = nil,
              rotation = 0,
              u1 = 0,
              v1 = 0,
              u2 = 1,
              v2 = 1,
              EventHandlerFile = "",
              EventHandlers = {},
              EventHandlerNames = {},
              Children = {
                {
                  name = "top",
                  x1 = 318,
                  y1 = 218,
                  x2 = 322,
                  y2 = 228,
                  RedLevel = 255,
                  GreenLevel = 255,
                  BlueLevel = 255,
                  TranslucencyLevel = 255,
                  HorizontalAnchor = "center",
                  VerticalAnchor = "center",
                  visible = 1,
                  container = false,
                  WidgetType = "image",
                  rotation = 0,
                  u1 = 0.509766,
                  v1 = 0.589844,
                  u2 = 0.517578,
                  v2 = 0.611328,
                  EventHandlerFile = "",
                  EventHandlers = {},
                  EventHandlerNames = {},
                  Children = {}
                },
                {
                  name = "right",
                  x1 = 328,
                  y1 = 234,
                  x2 = 338,
                  y2 = 238,
                  RedLevel = 255,
                  GreenLevel = 255,
                  BlueLevel = 255,
                  TranslucencyLevel = 255,
                  HorizontalAnchor = "center",
                  VerticalAnchor = "center",
                  visible = 1,
                  container = false,
                  WidgetType = "image",
                  rotation = 0,
                  u1 = 0.539063,
                  v1 = 0.632813,
                  u2 = 0.560547,
                  v2 = 0.640625,
                  EventHandlerFile = "",
                  EventHandlers = {},
                  EventHandlerNames = {},
                  Children = {}
                },
                {
                  name = "bottom",
                  x1 = 318,
                  y1 = 244,
                  x2 = 322,
                  y2 = 254,
                  RedLevel = 255,
                  GreenLevel = 255,
                  BlueLevel = 255,
                  TranslucencyLevel = 255,
                  HorizontalAnchor = "center",
                  VerticalAnchor = "center",
                  visible = 1,
                  container = false,
                  WidgetType = "image",
                  rotation = 0,
                  u1 = 0.509766,
                  v1 = 0.662109,
                  u2 = 0.517578,
                  v2 = 0.683594,
                  EventHandlerFile = "",
                  EventHandlers = {},
                  EventHandlerNames = {},
                  Children = {}
                },
                {
                  name = "left",
                  x1 = 302,
                  y1 = 234,
                  x2 = 312,
                  y2 = 238,
                  RedLevel = 255,
                  GreenLevel = 255,
                  BlueLevel = 255,
                  TranslucencyLevel = 255,
                  HorizontalAnchor = "center",
                  VerticalAnchor = "center",
                  visible = 1,
                  container = false,
                  WidgetType = "image",
                  rotation = 0,
                  u1 = 0.466797,
                  v1 = 0.632813,
                  u2 = 0.488281,
                  v2 = 0.640625,
                  EventHandlerFile = "",
                  EventHandlers = {},
                  EventHandlerNames = {},
                  Children = {}
                }
              }
            }
          }
        }
      }
    },
    {
      name = "compass",
      x1 = 80,
      y1 = 72,
      x2 = 104,
      y2 = 120,
      RedLevel = 201,
      GreenLevel = 201,
      BlueLevel = 201,
      TranslucencyLevel = 168,
      HorizontalAnchor = "left",
      VerticalAnchor = "top",
      visible = 1,
      container = false,
      WidgetType = "image",
      texture = "satellite_compass",
      textureFile = "D:/projects/Branches/Snapshot/Data/Src/Map/GLOBAL/HUD/TEXTURES/satellite_compass.tga",
      rotation = 0,
      u1 = 0,
      v1 = 0,
      u2 = 1,
      v2 = 1,
      EventHandlerFile = "",
      EventHandlers = {},
      EventHandlerNames = {},
      Children = {}
    },
    {
      name = "Z Indicator",
      x1 = 80,
      y1 = 136,
      x2 = 112,
      y2 = 360,
      RedLevel = 201,
      GreenLevel = 201,
      BlueLevel = 201,
      TranslucencyLevel = 168,
      HorizontalAnchor = "left",
      VerticalAnchor = "top",
      visible = 1,
      container = false,
      WidgetType = "image",
      texture = "satellite_meter_tile_side",
      textureFile = "D:/projects/Branches/Snapshot/Data/Src/Map/GLOBAL/HUD/TEXTURES/satellite_meter_tile_side.tga",
      rotation = 0,
      u1 = 0,
      v1 = 0,
      u2 = 1,
      v2 = 8,
      EventHandlerFile = "MrxGuiSatellite",
      EventHandlers = {
        GuiInitialization = MrxGuiSatellite.InitMeter,
        GuiUpdate = MrxGuiSatellite.HandleZUpdate
      },
      EventHandlerNames = {
        GuiInitialization = "InitMeter",
        GuiUpdate = "HandleZUpdate"
      },
      Children = {
        {
          name = "Pointer",
          x1 = 104,
          y1 = 220,
          x2 = 128,
          y2 = 244,
          RedLevel = 201,
          GreenLevel = 201,
          BlueLevel = 201,
          TranslucencyLevel = 168,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = "satellite_meter_triangle",
          textureFile = "D:/projects/Branches/Snapshot/Data/Src/Map/GLOBAL/HUD/TEXTURES/satellite_meter_triangle.tga",
          rotation = 270,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "z readout",
          x1 = 136,
          y1 = 223,
          x2 = 164,
          y2 = 239,
          RedLevel = 201,
          GreenLevel = 201,
          BlueLevel = 201,
          TranslucencyLevel = 168,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "text",
          text = "100",
          font = "english_18",
          scale = 1,
          Justification = "left",
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "top frame",
          x1 = 80,
          y1 = 136,
          x2 = 108,
          y2 = 138,
          RedLevel = 201,
          GreenLevel = 201,
          BlueLevel = 201,
          TranslucencyLevel = 168,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "bottom frame",
          x1 = 80,
          y1 = 358,
          x2 = 108,
          y2 = 360,
          RedLevel = 201,
          GreenLevel = 201,
          BlueLevel = 201,
          TranslucencyLevel = 168,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        }
      }
    },
    {
      name = "X Indicator",
      x1 = 160,
      y1 = 40,
      x2 = 480,
      y2 = 72,
      RedLevel = 201,
      GreenLevel = 201,
      BlueLevel = 201,
      TranslucencyLevel = 168,
      HorizontalAnchor = "left",
      VerticalAnchor = "top",
      visible = 1,
      container = false,
      WidgetType = "image",
      texture = "satellite_meter_tile",
      textureFile = "D:/projects/Branches/Snapshot/Data/Src/Map/GLOBAL/HUD/TEXTURES/satellite_meter_tile.tga",
      rotation = 0,
      u1 = 0,
      v1 = 0,
      u2 = 10,
      v2 = 1,
      EventHandlerFile = "MrxGuiSatellite",
      EventHandlers = {
        GuiUpdate = MrxGuiSatellite.HandleXUpdate,
        GuiInitialization = MrxGuiSatellite.InitMeter
      },
      EventHandlerNames = {
        GuiUpdate = "HandleXUpdate",
        GuiInitialization = "InitMeter"
      },
      Children = {
        {
          name = "Pointer",
          x1 = 308,
          y1 = 64,
          x2 = 332,
          y2 = 88,
          RedLevel = 201,
          GreenLevel = 201,
          BlueLevel = 201,
          TranslucencyLevel = 168,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = "satellite_meter_triangle",
          textureFile = "D:/projects/Branches/Snapshot/Data/Src/Map/GLOBAL/HUD/TEXTURES/satellite_meter_triangle.tga",
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "New Text",
          x1 = 308,
          y1 = 90,
          x2 = 358,
          y2 = 106,
          RedLevel = 201,
          GreenLevel = 201,
          BlueLevel = 201,
          TranslucencyLevel = 168,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "text",
          text = "100",
          font = "english_18",
          scale = 1,
          Justification = "left",
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "left frame",
          x1 = 160,
          y1 = 40,
          x2 = 162,
          y2 = 68,
          RedLevel = 201,
          GreenLevel = 201,
          BlueLevel = 201,
          TranslucencyLevel = 168,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "right frame",
          x1 = 478,
          y1 = 40,
          x2 = 480,
          y2 = 68,
          RedLevel = 201,
          GreenLevel = 201,
          BlueLevel = 201,
          TranslucencyLevel = 168,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        }
      }
    },
    {
      name = "Time of op",
      x1 = 464,
      y1 = 320,
      x2 = 592,
      y2 = 374,
      RedLevel = 96,
      GreenLevel = 96,
      BlueLevel = 96,
      TranslucencyLevel = 128,
      HorizontalAnchor = "right",
      VerticalAnchor = "bottom",
      visible = 1,
      container = true,
      WidgetType = "image",
      texture = nil,
      textureFile = nil,
      rotation = 0,
      u1 = 0,
      v1 = 0,
      u2 = 1,
      v2 = 1,
      EventHandlerFile = "",
      EventHandlers = {},
      EventHandlerNames = {},
      Children = {
        {
          name = "time label",
          x1 = 385,
          y1 = 322,
          x2 = 585,
          y2 = 338,
          RedLevel = 255,
          GreenLevel = 255,
          BlueLevel = 255,
          TranslucencyLevel = 255,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "text",
          text = "[Satellite.Time]",
          font = "english_20",
          scale = 0.6,
          Justification = "right",
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "Time number",
          x1 = 385,
          y1 = 340,
          x2 = 585,
          y2 = 356,
          RedLevel = 255,
          GreenLevel = 255,
          BlueLevel = 255,
          TranslucencyLevel = 255,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "text",
          text = "00:00:00",
          font = "english_20",
          scale = 1,
          Justification = "right",
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "top frame",
          x1 = 464,
          y1 = 320,
          x2 = 592,
          y2 = 322,
          RedLevel = 201,
          GreenLevel = 201,
          BlueLevel = 201,
          TranslucencyLevel = 168,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "left frame",
          x1 = 464,
          y1 = 322,
          x2 = 466,
          y2 = 372,
          RedLevel = 201,
          GreenLevel = 201,
          BlueLevel = 201,
          TranslucencyLevel = 168,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "bottom frame",
          x1 = 464,
          y1 = 372,
          x2 = 592,
          y2 = 374,
          RedLevel = 201,
          GreenLevel = 201,
          BlueLevel = 201,
          TranslucencyLevel = 168,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "right frame",
          x1 = 590,
          y1 = 322,
          x2 = 592,
          y2 = 372,
          RedLevel = 201,
          GreenLevel = 201,
          BlueLevel = 201,
          TranslucencyLevel = 168,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        }
      }
    },
    {
      name = "Cost of op",
      x1 = 464,
      y1 = 384,
      x2 = 592,
      y2 = 438,
      RedLevel = 96,
      GreenLevel = 96,
      BlueLevel = 96,
      TranslucencyLevel = 128,
      HorizontalAnchor = "right",
      VerticalAnchor = "bottom",
      visible = 1,
      container = true,
      WidgetType = "image",
      texture = nil,
      textureFile = nil,
      rotation = 0,
      u1 = 0,
      v1 = 0,
      u2 = 1,
      v2 = 1,
      EventHandlerFile = "",
      EventHandlers = {},
      EventHandlerNames = {},
      Children = {
        {
          name = "cost label",
          x1 = 385,
          y1 = 386,
          x2 = 585,
          y2 = 402,
          RedLevel = 255,
          GreenLevel = 255,
          BlueLevel = 255,
          TranslucencyLevel = 255,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "text",
          text = "[Satellite.Cost]",
          font = "english_20",
          scale = 0.6,
          Justification = "right",
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "Cost Number",
          x1 = 385,
          y1 = 404,
          x2 = 585,
          y2 = 420,
          RedLevel = 255,
          GreenLevel = 255,
          BlueLevel = 255,
          TranslucencyLevel = 255,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "text",
          text = "10000",
          font = "english_20",
          scale = 1,
          Justification = "right",
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "top frame",
          x1 = 464,
          y1 = 384,
          x2 = 592,
          y2 = 386,
          RedLevel = 201,
          GreenLevel = 201,
          BlueLevel = 201,
          TranslucencyLevel = 168,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "left frame",
          x1 = 464,
          y1 = 386,
          x2 = 466,
          y2 = 436,
          RedLevel = 201,
          GreenLevel = 201,
          BlueLevel = 201,
          TranslucencyLevel = 168,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "bottom frame",
          x1 = 464,
          y1 = 436,
          x2 = 592,
          y2 = 438,
          RedLevel = 201,
          GreenLevel = 201,
          BlueLevel = 201,
          TranslucencyLevel = 168,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "right frame",
          x1 = 590,
          y1 = 386,
          x2 = 592,
          y2 = 436,
          RedLevel = 201,
          GreenLevel = 201,
          BlueLevel = 201,
          TranslucencyLevel = 168,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        }
      }
    },
    {
      name = "Target text",
      x1 = 80,
      y1 = 376,
      x2 = 138,
      y2 = 392,
      RedLevel = 255,
      GreenLevel = 255,
      BlueLevel = 255,
      TranslucencyLevel = 255,
      HorizontalAnchor = "left",
      VerticalAnchor = "top",
      visible = 1,
      container = false,
      WidgetType = "text",
      text = " ",
      font = "english_18",
      scale = 1,
      Justification = "left",
      EventHandlerFile = "MrxGuiSatellite",
      EventHandlers = {
        SatelliteTargetUpdate = MrxGuiSatellite.HandleReadoutUpdate
      },
      EventHandlerNames = {
        SatelliteTargetUpdate = "HandleReadoutUpdate"
      },
      Children = {}
    },
    {
      name = "Target faction",
      x1 = 50,
      y1 = 368,
      x2 = 80,
      y2 = 398,
      RedLevel = 255,
      GreenLevel = 255,
      BlueLevel = 255,
      TranslucencyLevel = 255,
      HorizontalAnchor = "left",
      VerticalAnchor = "top",
      visible = -1,
      container = false,
      WidgetType = "image",
      texture = nil,
      textureFile = nil,
      rotation = 0,
      u1 = 0,
      v1 = 0,
      u2 = 1,
      v2 = 1,
      EventHandlerFile = "MrxGuiSatellite",
      EventHandlers = {
        SatelliteTargetUpdate = MrxGuiSatellite.HandleFactionUpdate
      },
      EventHandlerNames = {
        SatelliteTargetUpdate = "HandleFactionUpdate"
      },
      Children = {}
    },
    {
      name = "satdesc",
      x1 = 50,
      y1 = 400,
      x2 = 450,
      y2 = 416,
      RedLevel = 255,
      GreenLevel = 255,
      BlueLevel = 255,
      TranslucencyLevel = 255,
      HorizontalAnchor = "left",
      VerticalAnchor = "bottom",
      visible = 1,
      container = false,
      WidgetType = "text",
      text = " ",
      font = "english_18",
      scale = 1,
      Justification = "left",
      EventHandlerFile = "",
      EventHandlers = {},
      EventHandlerNames = {},
      Children = {}
    },
    {
      name = "found",
      x1 = 0,
      y1 = 0,
      x2 = 128,
      y2 = 128,
      RedLevel = 255,
      GreenLevel = 255,
      BlueLevel = 255,
      TranslucencyLevel = 0,
      HorizontalAnchor = "center",
      VerticalAnchor = "center",
      visible = 1,
      container = true,
      WidgetType = "image",
      texture = nil,
      textureFile = nil,
      rotation = 0,
      u1 = 0,
      v1 = 0,
      u2 = 1,
      v2 = 1,
      EventHandlerFile = "",
      EventHandlers = {},
      EventHandlerNames = {},
      Children = {
        {
          name = "ftop",
          x1 = 0,
          y1 = 0,
          x2 = 128,
          y2 = 2,
          RedLevel = 255,
          GreenLevel = 255,
          BlueLevel = 255,
          TranslucencyLevel = 255,
          HorizontalAnchor = "center",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "fleft",
          x1 = 0,
          y1 = 0,
          x2 = 2,
          y2 = 128,
          RedLevel = 255,
          GreenLevel = 255,
          BlueLevel = 255,
          TranslucencyLevel = 255,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "fbottom",
          x1 = 0,
          y1 = 126,
          x2 = 128,
          y2 = 128,
          RedLevel = 255,
          GreenLevel = 255,
          BlueLevel = 255,
          TranslucencyLevel = 255,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        },
        {
          name = "fright",
          x1 = 126,
          y1 = 0,
          x2 = 128,
          y2 = 128,
          RedLevel = 255,
          GreenLevel = 255,
          BlueLevel = 255,
          TranslucencyLevel = 255,
          HorizontalAnchor = "left",
          VerticalAnchor = "top",
          visible = 1,
          container = false,
          WidgetType = "image",
          texture = nil,
          textureFile = nil,
          rotation = 0,
          u1 = 0,
          v1 = 0,
          u2 = 1,
          v2 = 1,
          EventHandlerFile = "",
          EventHandlers = {},
          EventHandlerNames = {},
          Children = {}
        }
      }
    },
    {
      name = "Satellite Help",
      x1 = 464,
      y1 = 72,
      x2 = 576,
      y2 = 364,
      RedLevel = 255,
      GreenLevel = 255,
      BlueLevel = 255,
      TranslucencyLevel = 255,
      HorizontalAnchor = "right",
      VerticalAnchor = "center",
      visible = 1,
      container = false,
      WidgetType = "text",
      text = " ",
      font = "english_18",
      scale = 1,
      Justification = "right",
      EventHandlerFile = "",
      EventHandlers = {
        GuiInitialization = MrxGuiSatellite.InitializeHelpField
      },
      EventHandlerNames = {
        GuiInitialization = "InitializeHelpField"
      },
      Children = {}
    }
  }
}
if import then
  import("MrxGuiBase")
end

function ReInit()
  for i in pairs(AddedWidgetList) do
    MrxGuiBase.RemoveWidget(AddedWidgetList[i])
  end
  AddedWidgetList = {}
  for i in pairs(LocalWidgetList) do
    MrxGuiBase.LoadAndAddWidgetFromLayoutFileData(LocalWidgetList[i], AddedWidgetList)
  end
end
