Type = "Time"
SubtitleData = {
  {
    0.45,
    "[Chris-Briefing-Cinematic-RecruitJet-03]"
  },
  {
    2.16,
    "[Fiona-Briefing-Cinematic-RecruitJet-04]"
  },
  {
    4.55,
    "[Chris-Briefing-Cinematic-RecruitJet-07]"
  },
  {
    6.53,
    "[Ewan-Briefing-Cinematic-RecruitJet-08]"
  },
  {
    7.88,
    "[Ewan-Briefing-Cinematic-RecruitJet-09]"
  },
  {
    11.03,
    "[Misha-Briefing-Cinematic-RecruitJet-10]"
  },
  {
    12.11,
    "[Ewan-Briefing-Cinematic-RecruitJet-11]"
  },
  {
    13.51,
    "[Misha-Briefing-Cinematic-RecruitJet-12]"
  },
  {
    15.81,
    "[Ewan-Briefing-Cinematic-RecruitJet-13]"
  },
  {
    18.15,
    "[Eva-Briefing-Cinematic-RecruitJet-14]"
  },
  {
    19.05,
    "[Ewan-Briefing-Cinematic-RecruitJet-15]"
  },
  {
    20.31,
    "[Misha-Briefing-Cinematic-RecruitJet-16]"
  },
  {
    21.61,
    "[Fiona-Briefing-Cinematic-RecruitJet-18]"
  },
  {
    23.96,
    "[Misha-Briefing-Cinematic-RecruitJet-19]"
  },
  {
    27.42,
    "[Chris-Briefing-Cinematic-RecruitJet-22]",
    6.04
  },
  {
    34.4,
    "[Fiona-Briefing-Cinematic-RecruitJet-23]"
  },
  {
    36.25,
    "[Fiona-Briefing-Cinematic-RecruitJet-27]"
  },
  {
    37.56,
    "[Chris-Briefing-Cinematic-RecruitJet-30]",
    5.24
  }
}
