Type = "Time"
SubtitleData = {
  {
    142.05,
    "[SHELL.Credits.CinematicLogoTitle]",
    2,
    true
  },
  {
    161.1,
    "[SHELL.Credits.Cinems.AssistantDirector]",
    2,
    true
  },
  {
    166.2,
    "[SHELL.Credits.Cinems.StoryEditor]",
    2,
    true
  },
  {
    173.21,
    "[SHELL.Credits.Cinems.Composer]",
    2,
    true
  },
  {
    180.11,
    "[SHELL.Credits.Cinems.AudioDirector]",
    2,
    true
  },
  {
    184.25,
    "[SHELL.Credits.Cinems.LeadProgrammer]",
    2,
    true
  },
  {
    191.02,
    "[SHELL.Credits.Cinems.TechnicalDirector]",
    2,
    true
  },
  {
    195.09,
    "[SHELL.Credits.Cinems.LeadAnimator]",
    2,
    true
  },
  {
    200.29,
    "[SHELL.Credits.Cinems.LeadArtist]",
    2,
    true
  },
  {
    208.13,
    "[SHELL.Credits.Cinems.LeadDesigner]",
    2,
    true
  },
  {
    214.23,
    "[SHELL.Credits.Cinems.ArtDirector]",
    2,
    true
  },
  {
    220.18,
    "[SHELL.Credits.Cinems.SeniorProducer]",
    2,
    true
  },
  {
    230,
    "[SHELL.Credits.Cinems.Director]",
    2,
    true
  },
  {
    1.93,
    "[Carmona-Briefing-Cinematic-RescueCarmona-01]"
  },
  {
    3.54,
    "[Jennifer-Briefing-Cinematic-RescueCarmona-03]"
  },
  {
    4.42,
    "[Carmona-Briefing-Cinematic-RescueCarmona-08]"
  },
  {
    5.68,
    "[Jennifer-Briefing-Cinematic-RescueCarmona-10]"
  },
  {
    6.82,
    "[Carmona-Briefing-Cinematic-RescueCarmona-12]"
  },
  {
    13.38,
    "[Blanco-Briefing-Cinematic-Betrayed-02]"
  },
  {
    17.43,
    "[Jennifer-Briefing-Cinematic-Betrayed-08]"
  },
  {
    22.6,
    "[Solano-Briefing-Cinematic-Betrayed-10]"
  },
  {
    26.14,
    "[Blanco-Briefing-Cinematic-Betrayed-11]"
  },
  {
    27.91,
    "[Solano-Briefing-Cinematic-Betrayed-13]"
  },
  {
    30.81,
    "[Jennifer-Briefing-Cinematic-Betrayed-16]"
  },
  {
    32.07,
    "[Solano-Briefing-Cinematic-Betrayed-18]"
  },
  {
    34.47,
    "[Solano-Briefing-Cinematic-Betrayed-19]"
  },
  {
    38.39,
    "[Solano-Briefing-Cinematic-Betrayed-23]"
  },
  {
    43.82,
    "[Jennifer-Briefing-Cinematic-Betrayed-25]"
  },
  {
    45.96,
    "[Solano-Briefing-Cinematic-Betrayed-27]",
    6.98
  },
  {
    52.91,
    "[Jennifer-Briefing-Cinematic-Betrayed-29]"
  },
  {
    57.2,
    "[Blanco-Briefing-Cinematic-Betrayed-35]"
  },
  {
    58.34,
    "[Jennifer-Briefing-Cinematic-Betrayed-38]"
  },
  {
    64.4,
    "[Solano-Briefing-Cinematic-Betrayed-43]",
    1.5
  },
  {
    78.29,
    "[Newscaster-Briefing-Cinematic-BackAtTheBar-42]",
    9.28
  },
  {
    87.25,
    "[Fiona-Briefing-Cinematic-BackAtTheBar-08]"
  },
  {
    88.9,
    "[Chris-Briefing-Cinematic-BackAtTheBar-11]"
  },
  {
    91.42,
    "[Jennifer-Briefing-Cinematic-BackAtTheBar-14]"
  },
  {
    93.19,
    "[Fiona-Briefing-Cinematic-BackAtTheBar-19]"
  },
  {
    94.83,
    "[Jennifer-Briefing-Cinematic-BackAtTheBar-21]"
  },
  {
    95.72,
    "[Fiona-Briefing-Cinematic-BackAtTheBar-23]"
  },
  {
    99,
    "[Jennifer-Briefing-Cinematic-BackAtTheBar-25]"
  },
  {
    102.28,
    "[Chris-Briefing-Cinematic-BackAtTheBar-28]"
  },
  {
    105.44,
    "[Mattias-Briefing-Cinematic-BackAtTheBar-31]"
  },
  {
    108.47,
    "[Newscaster-Briefing-Cinematic-BackAtTheBar-33]"
  },
  {
    113.01,
    "[Solano-Briefing-Cinematic-BackAtTheBar-34]",
    14.5
  },
  {
    127.79,
    "[Jennifer-Briefing-Cinematic-BackAtTheBar-36]"
  },
  {
    133.72,
    "[Solano-Briefing-Cinematic-BackAtTheBar-38]"
  },
  {
    135.11,
    "[Jennifer-Briefing-Cinematic-BackAtTheBar-40]"
  },
  {
    144.38,
    "[ReporterNeutral.Credits02]"
  },
  {
    148.8,
    "[ReporterAntiSolano.Credits09]"
  },
  {
    150.79,
    "[ReporterProSolano.Credits02]"
  },
  {
    153.91,
    "[ReporterNeutral.Credits03]"
  },
  {
    159.64,
    "[ReporterProSolano.Credits03]"
  },
  {
    162.76,
    "[ReporterAntiSolano.Credits07]"
  },
  {
    165.36,
    "[ReporterAntiSolano.Credits08]"
  },
  {
    168.4,
    "[ReporterNeutral.Credits07]"
  },
  {
    173.94,
    "[ReporterProSolano.Credits11]"
  },
  {
    178.02,
    "[ReporterNeutral.Credits04]"
  },
  {
    183.83,
    "[ReporterProSolano.Credits05]"
  },
  {
    187.3,
    "[ReporterAntiSolano.Credits04]"
  },
  {
    192.24,
    "[ReporterProSolano.Credits06]"
  },
  {
    195.54,
    "[ReporterNeutral.Credits05]"
  },
  {
    200.48,
    "[ReporterAntiSolano.Credits03]"
  },
  {
    203.34,
    "[ReporterNeutral.Credits09]"
  },
  {
    208.2,
    "[ReporterProSolano.Credits07]"
  },
  {
    211.06,
    "[ReporterNeutral.Credits10]"
  },
  {
    219.55,
    "[Solano-Briefing-Cinematic-BackAtTheBar-43]"
  }
}
