Type = "Time"
SubtitleData = {
  {
    0.15,
    "[Ewan-Briefing-Cinematic-RecruitHeli-01]",
    4.49
  },
  {
    4.44,
    "[Fiona-Briefing-Cinematic-RecruitHeli-02]"
  },
  {
    5.83,
    "[Ewan-Briefing-Cinematic-RecruitHeli-03]"
  },
  {
    10.46,
    "[Jennifer-Briefing-Cinematic-RecruitHeli-05]"
  },
  {
    12.77,
    "[Ewan-Briefing-Cinematic-RecruitHeli-08]"
  },
  {
    16.48,
    "[Jennifer-Briefing-Cinematic-RecruitHeli-11]"
  },
  {
    18.95,
    "[Fiona-Briefing-Cinematic-RecruitHeli-13]"
  },
  {
    21.11,
    "[Ewan-Briefing-Cinematic-RecruitHeli-14]"
  },
  {
    22.54,
    "[Fiona-Briefing-Cinematic-RecruitHeli-15]"
  },
  {
    24.39,
    "[Ewan-Briefing-Cinematic-RecruitHeli-16]"
  },
  {
    28.98,
    "[Jennifer-Briefing-Cinematic-RecruitHeli-19]"
  },
  {
    32.11,
    "[Fiona-Briefing-Cinematic-RecruitHeli-21]"
  }
}
