Type = "Time"
SubtitleData = {
  {
    0.15,
    "[Ewan-Briefing-Cinematic-RecruitHeli-01]",
    4.49
  },
  {
    4.63,
    "[Fiona-Briefing-Cinematic-RecruitHeli-02]"
  },
  {
    6,
    "[Ewan-Briefing-Cinematic-RecruitHeli-03]"
  },
  {
    10.59,
    "[Mattias-Briefing-Cinematic-RecruitHeli-04]"
  },
  {
    13.65,
    "[Ewan-Briefing-Cinematic-RecruitHeli-09]"
  },
  {
    16.33,
    "[Mattias-Briefing-Cinematic-RecruitHeli-10]"
  },
  {
    18.32,
    "[Fiona-Briefing-Cinematic-RecruitHeli-13]"
  },
  {
    20.5,
    "[Ewan-Briefing-Cinematic-RecruitHeli-14]"
  },
  {
    21.76,
    "[Fiona-Briefing-Cinematic-RecruitHeli-15]"
  },
  {
    23.75,
    "[Ewan-Briefing-Cinematic-RecruitHeli-16]"
  },
  {
    28.41,
    "[Mattias-Briefing-Cinematic-RecruitHeli-18]"
  },
  {
    31.7,
    "[Fiona-Briefing-Cinematic-RecruitHeli-21]"
  }
}
