Type = "Time"
SubtitleData = {
  {
    0.47,
    "[Ewan-Briefing-Cinematic-RecuitMechanic-01]"
  },
  {
    4.14,
    "[Fiona-Briefing-Cinematic-RecuitMechanic-02]"
  },
  {
    8.91,
    "[Fiona-Briefing-Cinematic-RecuitMechanic-03]"
  },
  {
    10.6,
    "[Eva-Briefing-Cinematic-RecuitMechanic-04]"
  },
  {
    14.97,
    "[Jennifer-Briefing-Cinematic-RecuitMechanic-06]"
  },
  {
    16.24,
    "[Ewan-Briefing-Cinematic-RecuitMechanic-08]"
  },
  {
    17.06,
    "[Fiona-Briefing-Cinematic-RecuitMechanic-09]"
  },
  {
    18.28,
    "[Jennifer-Briefing-Cinematic-RecuitMechanic-12]"
  },
  {
    19.91,
    "[Fiona-Briefing-Cinematic-RecuitMechanic-14]"
  },
  {
    21.95,
    "[Eva-Briefing-Cinematic-RecuitMechanic-15]"
  },
  {
    23.99,
    "[Fiona-Briefing-Cinematic-RecuitMechanic-24]"
  },
  {
    25.49,
    "[Ewan-Briefing-Cinematic-RecuitMechanic-18]"
  },
  {
    26.81,
    "[Eva-Briefing-Cinematic-RecuitMechanic-19]"
  }
}
