Type = "Time"
SubtitleData = {
  {
    1.17,
    "[Jennifer-Briefing-Cinematic-RecruitJet-02]"
  },
  {
    2.2,
    "[Fiona-Briefing-Cinematic-RecruitJet-04]"
  },
  {
    4.77,
    "[Jennifer-Briefing-Cinematic-RecruitJet-06]"
  },
  {
    6.83,
    "[Ewan-Briefing-Cinematic-RecruitJet-08]"
  },
  {
    8.09,
    "[Ewan-Briefing-Cinematic-RecruitJet-09]"
  },
  {
    10.97,
    "[Misha-Briefing-Cinematic-RecruitJet-10]"
  },
  {
    12.55,
    "[Ewan-Briefing-Cinematic-RecruitJet-11]"
  },
  {
    13.8,
    "[Misha-Briefing-Cinematic-RecruitJet-12]"
  },
  {
    16.41,
    "[Ewan-Briefing-Cinematic-RecruitJet-13]"
  },
  {
    18.57,
    "[Eva-Briefing-Cinematic-RecruitJet-14]"
  },
  {
    19.47,
    "[Ewan-Briefing-Cinematic-RecruitJet-15]"
  },
  {
    20.64,
    "[Misha-Briefing-Cinematic-RecruitJet-16]"
  },
  {
    21.94,
    "[Fiona-Briefing-Cinematic-RecruitJet-18]"
  },
  {
    24.46,
    "[Misha-Briefing-Cinematic-RecruitJet-19]"
  },
  {
    27.88,
    "[Jennifer-Briefing-Cinematic-RecruitJet-21]",
    5.1
  },
  {
    34.58,
    "[Fiona-Briefing-Cinematic-RecruitJet-23]"
  },
  {
    36.06,
    "[Fiona-Briefing-Cinematic-RecruitJet-26]"
  },
  {
    38.04,
    "[Jennifer-Briefing-Cinematic-RecruitJet-29]",
    3.84
  }
}
