Type = "Time"
SubtitleData = {
  {
    1.06,
    "[Joyce-Briefing-Cinematic-AlliesVictory-02]"
  },
  {
    3.61,
    "[Chris-Briefing-Cinematic-AlliesVictory-05]"
  },
  {
    6.11,
    "[Joyce-Briefing-Cinematic-AlliesVictory-08]",
    10
  },
  {
    16.27,
    "[Chris-Briefing-Cinematic-AlliesVictory-11]"
  },
  {
    23.28,
    "[Joyce-Briefing-Cinematic-AlliesVictory-12]"
  },
  {
    29.02,
    "[Chris-Briefing-Cinematic-AlliesVictory-15]"
  },
  {
    29.56,
    "[Fiona-Briefing-Cinematic-AlliesVictory-16]"
  },
  {
    33.28,
    "[Solano-Briefing-Cinematic-AlliesVictory-17]"
  },
  {
    41.04,
    "[Chris-Briefing-Cinematic-AlliesVictory-23]"
  },
  {
    43.85,
    "[Joyce-Briefing-Cinematic-AlliesVictory-26]",
    9.18
  },
  {
    52.997,
    "[Chris-Briefing-Cinematic-AlliesVictory-29]"
  }
}
