Type = "Time"
SubtitleData = {
  {
    1.13,
    "[Joyce-Briefing-Cinematic-AlliesVictory-02]"
  },
  {
    3.82,
    "[Mattias-Briefing-Cinematic-AlliesVictory-03]"
  },
  {
    6.39,
    "[Joyce-Briefing-Cinematic-AlliesVictory-08]",
    8.7
  },
  {
    15.11,
    "[Mattias-Briefing-Cinematic-AlliesVictory-09]"
  },
  {
    22.53,
    "[Joyce-Briefing-Cinematic-AlliesVictory-12]"
  },
  {
    26.71,
    "[Mattias-Briefing-Cinematic-AlliesVictory-13]"
  },
  {
    27.54,
    "[Fiona-Briefing-Cinematic-AlliesVictory-16]"
  },
  {
    31.66,
    "[Solano-Briefing-Cinematic-AlliesVictory-17]"
  },
  {
    38.88,
    "[Mattias-Briefing-Cinematic-AlliesVictory-21]"
  },
  {
    41.61,
    "[Joyce-Briefing-Cinematic-AlliesVictory-24]",
    9.18
  },
  {
    51.1,
    "[Mattias-Briefing-Cinematic-AlliesVictory-27]"
  }
}
