Type = "Time"
SubtitleData = {
  {
    0.2,
    "[Ewan-Briefing-Cinematic-RecruitHeli-01]",
    4.49
  },
  {
    4.62,
    "[Fiona-Briefing-Cinematic-RecruitHeli-02]"
  },
  {
    5.93,
    "[Ewan-Briefing-Cinematic-RecruitHeli-03]"
  },
  {
    10.87,
    "[Chris-Briefing-Cinematic-RecruitHeli-06]"
  },
  {
    13.4,
    "[Ewan-Briefing-Cinematic-RecruitHeli-09]"
  },
  {
    17.11,
    "[Chris-Briefing-Cinematic-RecruitHeli-12]"
  },
  {
    19.56,
    "[Fiona-Briefing-Cinematic-RecruitHeli-13]"
  },
  {
    21.77,
    "[Ewan-Briefing-Cinematic-RecruitHeli-14]"
  },
  {
    23.47,
    "[Fiona-Briefing-Cinematic-RecruitHeli-15]"
  },
  {
    25.09,
    "[Ewan-Briefing-Cinematic-RecruitHeli-16]"
  },
  {
    29.68,
    "[Chris-Briefing-Cinematic-RecruitHeli-20]"
  },
  {
    32.996,
    "[Fiona-Briefing-Cinematic-RecruitHeli-21]"
  }
}
