Type = "Time"
SubtitleData = {
  {
    145,
    "[SHELL.Credits.CinematicLogoTitle]",
    2,
    true
  },
  {
    164.1,
    "[SHELL.Credits.Cinems.AssistantDirector]",
    2,
    true
  },
  {
    169.2,
    "[SHELL.Credits.Cinems.StoryEditor]",
    2,
    true
  },
  {
    176.16,
    "[SHELL.Credits.Cinems.Composer]",
    2,
    true
  },
  {
    183,
    "[SHELL.Credits.Cinems.AudioDirector]",
    2,
    true
  },
  {
    187,
    "[SHELL.Credits.Cinems.LeadProgrammer]",
    2,
    true
  },
  {
    192.25,
    "[SHELL.Credits.Cinems.TechnicalDirector]",
    2,
    true
  },
  {
    198,
    "[SHELL.Credits.Cinems.LeadAnimator]",
    2,
    true
  },
  {
    202.25,
    "[SHELL.Credits.Cinems.LeadArtist]",
    2,
    true
  },
  {
    211,
    "[SHELL.Credits.Cinems.LeadDesigner]",
    2,
    true
  },
  {
    217.2,
    "[SHELL.Credits.Cinems.ArtDirector]",
    2,
    true
  },
  {
    223,
    "[SHELL.Credits.Cinems.SeniorProducer]",
    2,
    true
  },
  {
    232.2,
    "[SHELL.Credits.Cinems.Director]",
    2,
    true
  },
  {
    2.06,
    "[Carmona-Briefing-Cinematic-RescueCarmona-01]"
  },
  {
    3.48,
    "[Mattias-Briefing-Cinematic-RescueCarmona-02]"
  },
  {
    6.38,
    "[Carmona-Briefing-Cinematic-RescueCarmona-08]"
  },
  {
    7.79,
    "[Mattias-Briefing-Cinematic-RescueCarmona-09]"
  },
  {
    9.08,
    "[Carmona-Briefing-Cinematic-RescueCarmona-12]",
    5.16
  },
  {
    14.75,
    "[Blanco-Briefing-Cinematic-Betrayed-01]",
    4.33
  },
  {
    19.71,
    "[Mattias-Briefing-Cinematic-Betrayed-07]",
    5.11
  },
  {
    25,
    "[Solano-Briefing-Cinematic-Betrayed-10]"
  },
  {
    28.15,
    "[Blanco-Briefing-Cinematic-Betrayed-11]"
  },
  {
    29.96,
    "[Solano-Briefing-Cinematic-Betrayed-12]"
  },
  {
    33.69,
    "[Mattias-Briefing-Cinematic-Betrayed-15]"
  },
  {
    34.92,
    "[Solano-Briefing-Cinematic-Betrayed-18]"
  },
  {
    37.56,
    "[Solano-Briefing-Cinematic-Betrayed-19]"
  },
  {
    42,
    "[Solano-Briefing-Cinematic-Betrayed-23]"
  },
  {
    47.61,
    "[Mattias-Briefing-Cinematic-Betrayed-24]"
  },
  {
    48.12,
    "[Solano-Briefing-Cinematic-Betrayed-27]",
    6.98
  },
  {
    55.08,
    "[Mattias-Briefing-Cinematic-Betrayed-28]"
  },
  {
    60.17,
    "[Blanco-Briefing-Cinematic-Betrayed-34]"
  },
  {
    61.52,
    "[Mattias-Briefing-Cinematic-Betrayed-37]"
  },
  {
    68.74,
    "[Solano-Briefing-Cinematic-Betrayed-43]",
    1.5
  },
  {
    82.72,
    "[Newscaster-Briefing-Cinematic-BackAtTheBar-42]",
    9.28
  },
  {
    91.74,
    "[Fiona-Briefing-Cinematic-BackAtTheBar-07]"
  },
  {
    93.93,
    "[Chris-Briefing-Cinematic-BackAtTheBar-10]"
  },
  {
    95.34,
    "[Mattias-Briefing-Cinematic-BackAtTheBar-13]"
  },
  {
    96.89,
    "[Fiona-Briefing-Cinematic-BackAtTheBar-19]"
  },
  {
    98.56,
    "[Mattias-Briefing-Cinematic-BackAtTheBar-20]"
  },
  {
    99.34,
    "[Fiona-Briefing-Cinematic-BackAtTheBar-23]"
  },
  {
    102.69,
    "[Mattias-Briefing-Cinematic-BackAtTheBar-24]"
  },
  {
    107.07,
    "[Chris-Briefing-Cinematic-BackAtTheBar-27]"
  },
  {
    109.52,
    "[Jennifer-Briefing-Cinematic-BackAtTheBar-30]"
  },
  {
    111.45,
    "[Newscaster-Briefing-Cinematic-BackAtTheBar-33]"
  },
  {
    115.83,
    "[Solano-Briefing-Cinematic-BackAtTheBar-34]",
    14.5
  },
  {
    130.52,
    "[Mattias-Briefing-Cinematic-BackAtTheBar-35]"
  },
  {
    136.57,
    "[Solano-Briefing-Cinematic-BackAtTheBar-38]"
  },
  {
    138.12,
    "[Mattias-Briefing-Cinematic-BackAtTheBar-39]"
  },
  {
    147.38,
    "[ReporterNeutral.Credits02]"
  },
  {
    151.8,
    "[ReporterAntiSolano.Credits09]"
  },
  {
    153.79,
    "[ReporterProSolano.Credits02]"
  },
  {
    156.91,
    "[ReporterNeutral.Credits03]"
  },
  {
    162.64,
    "[ReporterProSolano.Credits03]"
  },
  {
    165.76,
    "[ReporterAntiSolano.Credits07]"
  },
  {
    168.36,
    "[ReporterAntiSolano.Credits08]"
  },
  {
    171.4,
    "[ReporterNeutral.Credits07]"
  },
  {
    176.94,
    "[ReporterProSolano.Credits11]"
  },
  {
    181.02,
    "[ReporterNeutral.Credits04]"
  },
  {
    186.83,
    "[ReporterProSolano.Credits05]"
  },
  {
    190.3,
    "[ReporterAntiSolano.Credits04]"
  },
  {
    195.24,
    "[ReporterProSolano.Credits06]"
  },
  {
    198.54,
    "[ReporterNeutral.Credits05]"
  },
  {
    203.48,
    "[ReporterAntiSolano.Credits03]"
  },
  {
    206.34,
    "[ReporterNeutral.Credits09]"
  },
  {
    211.2,
    "[ReporterProSolano.Credits07]"
  },
  {
    214.06,
    "[ReporterNeutral.Credits10]"
  },
  {
    222.55,
    "[Solano-Briefing-Cinematic-BackAtTheBar-43]"
  }
}
