Type = "Time"
SubtitleData = {
  {
    150.05,
    "[SHELL.Credits.CinematicLogoTitle]",
    2,
    true
  },
  {
    169.1,
    "[SHELL.Credits.Cinems.AssistantDirector]",
    2,
    true
  },
  {
    174.2,
    "[SHELL.Credits.Cinems.StoryEditor]",
    2,
    true
  },
  {
    181.21,
    "[SHELL.Credits.Cinems.Composer]",
    2,
    true
  },
  {
    188.11,
    "[SHELL.Credits.Cinems.AudioDirector]",
    2,
    true
  },
  {
    191.25,
    "[SHELL.Credits.Cinems.LeadProgrammer]",
    2,
    true
  },
  {
    199.02,
    "[SHELL.Credits.Cinems.TechnicalDirector]",
    2,
    true
  },
  {
    203.09,
    "[SHELL.Credits.Cinems.LeadAnimator]",
    2,
    true
  },
  {
    208.29,
    "[SHELL.Credits.Cinems.LeadArtist]",
    2,
    true
  },
  {
    216.13,
    "[SHELL.Credits.Cinems.LeadDesigner]",
    2,
    true
  },
  {
    222.23,
    "[SHELL.Credits.Cinems.ArtDirector]",
    2,
    true
  },
  {
    228.18,
    "[SHELL.Credits.Cinems.SeniorProducer]",
    2,
    true
  },
  {
    238,
    "[SHELL.Credits.Cinems.Director]",
    2,
    true
  },
  {
    2,
    "[Carmona-Briefing-Cinematic-RescueCarmona-01]"
  },
  {
    3.48,
    "[Chris-Briefing-Cinematic-RescueCarmona-04]"
  },
  {
    6,
    "[Carmona-Briefing-Cinematic-RescueCarmona-08]"
  },
  {
    7.43,
    "[Chris-Briefing-Cinematic-RescueCarmona-11]"
  },
  {
    9.42,
    "[Carmona-Briefing-Cinematic-RescueCarmona-12]"
  },
  {
    15.52,
    "[Blanco-Briefing-Cinematic-Betrayed-03]"
  },
  {
    20.16,
    "[Jennifer-Briefing-Cinematic-Betrayed-08]"
  },
  {
    24.53,
    "[Solano-Briefing-Cinematic-Betrayed-10]"
  },
  {
    27.98,
    "[Blanco-Briefing-Cinematic-Betrayed-11]"
  },
  {
    29.57,
    "[Solano-Briefing-Cinematic-Betrayed-14]"
  },
  {
    33.29,
    "[Chris-Briefing-Cinematic-Betrayed-17]"
  },
  {
    34.75,
    "[Solano-Briefing-Cinematic-Betrayed-18]"
  },
  {
    37.27,
    "[Solano-Briefing-Cinematic-Betrayed-19]"
  },
  {
    41.64,
    "[Solano-Briefing-Cinematic-Betrayed-23]"
  },
  {
    47.08,
    "[Chris-Briefing-Cinematic-Betrayed-26]"
  },
  {
    48.27,
    "[Solano-Briefing-Cinematic-Betrayed-27]",
    6.98
  },
  {
    55.04,
    "[Chris-Briefing-Cinematic-Betrayed-30]"
  },
  {
    60.48,
    "[Blanco-Briefing-Cinematic-Betrayed-34]"
  },
  {
    61.4,
    "[Chris-Briefing-Cinematic-Betrayed-39]"
  },
  {
    66.31,
    "[Solano-Briefing-Cinematic-Betrayed-43]",
    1.5
  },
  {
    80.5,
    "[Newscaster-Briefing-Cinematic-BackAtTheBar-42]",
    9.28
  },
  {
    89.78,
    "[Fiona-Briefing-Cinematic-BackAtTheBar-09]"
  },
  {
    91.64,
    "[Jennifer-Briefing-Cinematic-BackAtTheBar-12]"
  },
  {
    93.63,
    "[Chris-Briefing-Cinematic-BackAtTheBar-15]"
  },
  {
    96.15,
    "[Fiona-Briefing-Cinematic-BackAtTheBar-19]"
  },
  {
    98.14,
    "[Chris-Briefing-Cinematic-BackAtTheBar-22]"
  },
  {
    98.93,
    "[Fiona-Briefing-Cinematic-BackAtTheBar-23]"
  },
  {
    102.12,
    "[Chris-Briefing-Cinematic-BackAtTheBar-26]"
  },
  {
    108.09,
    "[Mattias-Briefing-Cinematic-BackAtTheBar-29]"
  },
  {
    110.87,
    "[Jennifer-Briefing-Cinematic-BackAtTheBar-32]"
  },
  {
    115.51,
    "[Newscaster-Briefing-Cinematic-BackAtTheBar-33]"
  },
  {
    120.15,
    "[Solano-Briefing-Cinematic-BackAtTheBar-34]",
    14.5
  },
  {
    134.74,
    "[Chris-Briefing-Cinematic-BackAtTheBar-37]"
  },
  {
    140.84,
    "[Solano-Briefing-Cinematic-BackAtTheBar-38]"
  },
  {
    142.43,
    "[Chris-Briefing-Cinematic-BackAtTheBar-41]"
  },
  {
    151.38,
    "[ReporterNeutral.Credits02]"
  },
  {
    155.8,
    "[ReporterAntiSolano.Credits09]"
  },
  {
    157.79,
    "[ReporterProSolano.Credits02]"
  },
  {
    160.91,
    "[ReporterNeutral.Credits03]"
  },
  {
    166.64,
    "[ReporterProSolano.Credits03]"
  },
  {
    169.76,
    "[ReporterAntiSolano.Credits07]"
  },
  {
    172.36,
    "[ReporterAntiSolano.Credits08]"
  },
  {
    175.4,
    "[ReporterNeutral.Credits07]"
  },
  {
    180.94,
    "[ReporterProSolano.Credits11]"
  },
  {
    185.02,
    "[ReporterNeutral.Credits04]"
  },
  {
    190.83,
    "[ReporterProSolano.Credits05]"
  },
  {
    194.3,
    "[ReporterAntiSolano.Credits04]"
  },
  {
    199.24,
    "[ReporterProSolano.Credits06]"
  },
  {
    202.54,
    "[ReporterNeutral.Credits05]"
  },
  {
    207.48,
    "[ReporterAntiSolano.Credits03]"
  },
  {
    210.34,
    "[ReporterNeutral.Credits09]"
  },
  {
    215.2,
    "[ReporterProSolano.Credits07]"
  },
  {
    218.06,
    "[ReporterNeutral.Credits10]"
  },
  {
    226.55,
    "[Solano-Briefing-Cinematic-BackAtTheBar-43]"
  }
}
