Type = "Time"
SubtitleData = {
  {
    0.36,
    "[Ewan-Briefing-Cinematic-RecuitMechanic-01]"
  },
  {
    4.28,
    "[Fiona-Briefing-Cinematic-RecuitMechanic-02]"
  },
  {
    8.99,
    "[Fiona-Briefing-Cinematic-RecuitMechanic-03]"
  },
  {
    10.67,
    "[Eva-Briefing-Cinematic-RecuitMechanic-04]"
  },
  {
    14.99,
    "[Mattias-Briefing-Cinematic-RecuitMechanic-05]"
  },
  {
    17.29,
    "[Ewan-Briefing-Cinematic-RecuitMechanic-08]"
  },
  {
    18.3,
    "[Fiona-Briefing-Cinematic-RecuitMechanic-09]"
  },
  {
    19.34,
    "[Mattias-Briefing-Cinematic-RecuitMechanic-11]"
  },
  {
    21.09,
    "[Fiona-Briefing-Cinematic-RecuitMechanic-14]"
  },
  {
    22.87,
    "[Eva-Briefing-Cinematic-RecuitMechanic-15]"
  },
  {
    25.18,
    "[Fiona-Briefing-Cinematic-RecuitMechanic-24]"
  },
  {
    26.34,
    "[Ewan-Briefing-Cinematic-RecuitMechanic-18]"
  },
  {
    27.97,
    "[Eva-Briefing-Cinematic-RecuitMechanic-19]"
  }
}
