Type = "Time"
SubtitleData = {
  {
    0.25,
    "[Ewan-Briefing-Cinematic-RecuitMechanic-01]"
  },
  {
    4.21,
    "[Fiona-Briefing-Cinematic-RecuitMechanic-02]"
  },
  {
    8.95,
    "[Fiona-Briefing-Cinematic-RecuitMechanic-03]"
  },
  {
    10.55,
    "[Eva-Briefing-Cinematic-RecuitMechanic-04]"
  },
  {
    15.1,
    "[Chris-Briefing-Cinematic-RecuitMechanic-07]"
  },
  {
    16.72,
    "[Ewan-Briefing-Cinematic-RecuitMechanic-08]"
  },
  {
    17.41,
    "[Fiona-Briefing-Cinematic-RecuitMechanic-09]"
  },
  {
    18.47,
    "[Chris-Briefing-Cinematic-RecuitMechanic-13]"
  },
  {
    19.84,
    "[Fiona-Briefing-Cinematic-RecuitMechanic-14]"
  },
  {
    21.84,
    "[Eva-Briefing-Cinematic-RecuitMechanic-15]"
  },
  {
    23.81,
    "[Fiona-Briefing-Cinematic-RecuitMechanic-24]"
  },
  {
    25.4,
    "[Ewan-Briefing-Cinematic-RecuitMechanic-18]"
  },
  {
    26.61,
    "[Eva-Briefing-Cinematic-RecuitMechanic-19]"
  }
}
