Type = "Time"
SubtitleData = {
  {
    0.73,
    "[Mattias-Briefing-Cinematic-RecruitJet-01]"
  },
  {
    2.19,
    "[Fiona-Briefing-Cinematic-RecruitJet-04]"
  },
  {
    4.46,
    "[Mattias-Briefing-Cinematic-RecruitJet-05]"
  },
  {
    6.74,
    "[Ewan-Briefing-Cinematic-RecruitJet-08]"
  },
  {
    8.02,
    "[Ewan-Briefing-Cinematic-RecruitJet-09]"
  },
  {
    11.2,
    "[Misha-Briefing-Cinematic-RecruitJet-10]"
  },
  {
    12.11,
    "[Ewan-Briefing-Cinematic-RecruitJet-11]"
  },
  {
    13.39,
    "[Misha-Briefing-Cinematic-RecruitJet-12]"
  },
  {
    16.26,
    "[Ewan-Briefing-Cinematic-RecruitJet-13]"
  },
  {
    18.4,
    "[Eva-Briefing-Cinematic-RecruitJet-14]"
  },
  {
    19.31,
    "[Ewan-Briefing-Cinematic-RecruitJet-15]"
  },
  {
    20.54,
    "[Misha-Briefing-Cinematic-RecruitJet-16]"
  },
  {
    21.86,
    "[Fiona-Briefing-Cinematic-RecruitJet-18]"
  },
  {
    24.18,
    "[Misha-Briefing-Cinematic-RecruitJet-19]"
  },
  {
    27.73,
    "[Mattias-Briefing-Cinematic-RecruitJet-20]",
    6.91
  },
  {
    34.93,
    "[Fiona-Briefing-Cinematic-RecruitJet-23]"
  },
  {
    36.48,
    "[Fiona-Briefing-Cinematic-RecruitJet-25]"
  },
  {
    37.39,
    "[Mattias-Briefing-Cinematic-RecruitJet-28]",
    5.1
  }
}
