Type = "Time"
SubtitleData = {
  {
    1.63,
    "[Mattias-Briefing-Cinematic-YourNewHome-10]"
  },
  {
    3.9,
    "[Fiona-Briefing-Cinematic-YourNewHome-13]"
  },
  {
    6.73,
    "[Mattias-Briefing-Cinematic-YourNewHome-16]"
  },
  {
    9.3,
    "[Fiona-Briefing-Cinematic-YourNewHome-19]"
  },
  {
    12.08,
    "[Mattias-Briefing-Cinematic-YourNewHome-20]"
  },
  {
    13.88,
    "[Fiona-Briefing-Cinematic-YourNewHome-23]"
  },
  {
    16.2,
    "[Mattias-Briefing-Cinematic-YourNewHome-24]"
  },
  {
    17.94,
    "[Fiona-Briefing-Cinematic-YourNewHome-27]"
  },
  {
    20.32,
    "[Mattias-Briefing-Cinematic-YourNewHome-28]"
  },
  {
    22.69,
    "[Fiona-Briefing-Cinematic-YourNewHome-31]"
  },
  {
    26.24,
    "[Fiona-Briefing-Cinematic-YourNewHome-32]"
  },
  {
    27.7,
    "[Mattias-Briefing-Cinematic-YourNewHome-33]"
  }
}
