Type = "Time"
SubtitleData = {
  {
    1.14,
    "[Joyce-Briefing-Cinematic-AlliesVictory-02]"
  },
  {
    4.27,
    "[Jennifer-Briefing-Cinematic-AlliesVictory-04]"
  },
  {
    6.55,
    "[Joyce-Briefing-Cinematic-AlliesVictory-07]",
    7.27
  },
  {
    13.94,
    "[Jennifer-Briefing-Cinematic-AlliesVictory-10]"
  },
  {
    20.99,
    "[Joyce-Briefing-Cinematic-AlliesVictory-12]"
  },
  {
    25.8,
    "[Jennifer-Briefing-Cinematic-AlliesVictory-14]"
  },
  {
    26.3,
    "[Fiona-Briefing-Cinematic-AlliesVictory-16]"
  },
  {
    29.82,
    "[Solano-Briefing-Cinematic-AlliesVictory-17]"
  },
  {
    37.71,
    "[Jennifer-Briefing-Cinematic-AlliesVictory-22]"
  },
  {
    39.94,
    "[Joyce-Briefing-Cinematic-AlliesVictory-25]",
    9.23
  },
  {
    49.27,
    "[Jennifer-Briefing-Cinematic-AlliesVictory-28]"
  }
}
